spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
      - name: AuthenticationFilter
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/ecom/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: usersServiceCircuitBreaker
                fallbackUri: forward:/fallback/users-service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/ecom/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/product-service
        - id: jwt-service
          uri: lb://jwt-service
          predicates:
            - Path=/ecom/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: jwtServiceCircuitBreaker
                fallbackUri: forward:/fallback/jwt-service
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/ecom/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartServiceCircuitBreaker
                fallbackUri: forward:/fallback/cart-service

resilience4j:
  circuitbreaker:
    instances:
      usersServiceCircuitBreaker:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - java.lang.NullPointerException

      productServiceCircuitBreaker:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - java.lang.NullPointerException

      cartServiceCircuitBreaker:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - java.lang.NullPointerException
          
      jwtServiceCircuitBreaker:
        registerHealthIndicator: true
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - java.lang.NullPointerException

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

#logging.level.org.springframework.web: DEBUG
